### ISSUE TITLE
How to get fyers access token ? I have App I'd and secret key.

### ISSUE THREAD

**Issue by Dummyyummy120001** [Maran1947/Stockify#2]

**Comment by Dummyyummy120001** [comment]
I have app I'd and secret key, how to get access token ?

**Comment by VipulSingh1407** [comment]
same issue please help

**Comment by Maran1947** [comment]
To understand how to get the access_token, please visit [this link](https://myapi.fyers.in/docs#tag/Authentication-and-Login-Flow-User-Apps). Alternatively, you can use the Fyers Node.js library, which is available [here](https://www.npmjs.com/package/fyers-api-v3).
